### ISSUE TITLE
Expand to other torrent sources

### ISSUE THREAD

**Issue by Kabouik** [trianglecirclexyz/cthulhu#2]
Thanks for this tool, I was actively looking for exactly that some weeks ago, glad to find it on r/commandline today!

In Stremio, a GUI application that does similar things, Torrentio is a major source for torrents and seems to simply be the best for most movies or TV shows in terms of seeds and leechers, at least for 4K. Would it be feasible to expand `cthulhu` so that it can fetch magnets from Torrentio too (and possibly others in the future)?

**Comment by trianglecirclexyz** [comment]
I appreciate you trying the tool out.

From what I read, TorrentIO itself has a scraper that scrapes from other sources (nyaa.si, piratebay, etc), so it would be difficult to integrate that directly into cthulhu. What I can probably do instead is just add more sources manually. I'll do some more research to see if I can implement something similar to TorrentIO.

**Comment by Kabouik** [comment]
Oh, that makes sense. Actually I never really tried to go to torrentio directly outside Stremio, but that would explain why most sources usually appear as coming from torrentio itself. Thanks for your reply.

I'll keep using your tool anyway, it is pretty useful. My only concern is that peerflix seems to be unmaintained as opposed to webtorrent-cli that notflix uses, but on the other hand it's more minimal which I think is better.

**Comment by trianglecirclexyz** [comment]
Yeah, I also used peerflix because it had more features such as being able to play multiple files at once. If you prefer to switch to webtorrent, you can just change `os.system(f'peerflix --mpv -a \'{magnet_link}\'')` to `os.system(f'webtorrent --mpv \'{magnet_link}\'')` on line 53 easily enough. If peerflix starts causing any problems, I might make webtorrent the default.

**Comment by Kabouik** [comment]
Great to hear, makes `cthulhu` future-proof while keeping it minimal as long as possible. It could be an option with a default value (if the dependency is met) I guess. I read [here](https://github.com/noctuid/mpv-webtorrent-hook#comparison-with-peerflix-hook) that `webtorrent` is supposed to be faster than `peerflix` but I have no idea if that is true, and sensible.

While we're at it, I opened an issue at [`webtorrent`'s repository](https://github.com/webtorrent/webtorrent/issues/2238) for improving ssh use, but I'm wondering if this is something that could be done on `cthulhu` (or `notflix` in that case since I was thinking about `webtorrent`) side instead?

I posted there because I was thinking it could be done by altering the mpv command behind `webtorrent/peerflix magnet --mpv --remote` into something like `$TERMINAL -e bash -c "DISPLAY=:0 mpv localhost-url"`, but I failed to code that in node and maybe there could be easier ways if doing that into `cthulhu` instead? Let me know and I can open an issue here if that's relevant. Else I'll stop the off-topic here!

**Comment by trianglecirclexyz** [comment]
Hmm I was investigating some hacky ways for it to work via ssh directly from cthulhu, but was not successful. Might play around with it some more later down the line. Thanks for the suggestion.

**Comment by trianglecirclexyz** [comment]
Added support for new sources as explained by the most recent pull request (#8). Current sources are nyaa and 1337x, but more can be added fairly easily by adding a new class and including the necessary methods for parsing. Planning on making config file for changing the default source so users don't have to always specify `--source <source>`.
