### ISSUE TITLE
http://1337x.wtf is down

### ISSUE THREAD

**Issue by Itookmyprozac** [trianglecirclexyz/cthulhu#9]
In this [notflix issue](https://github.com/Bugswriter/notflix/issues/89) they're pointing the same problem.

The new domain is https://1337x.to

**Comment by trianglecirclexyz** [comment]
I fixed this in the latest commit (https://github.com/trianglecirclexyz/cthulhu/commit/731672acd8f35c4d26755937c133accf5c70493c). I changed the source from 1337x.wtf to 1337xx.to, but you can change it to 1337x.to instead in the script (or any other mirror).

**Comment by Itookmyprozac** [comment]
Good! Thanks.
